#!/usr/bin/bash

###
# Copyright 2016 Miler T. Lee, University of Pittburgh
# This file is part of the RESA Suite
#
# RESA Suite is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# RESA Suite is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with RESA Suite.  If not, see <http://www.gnu.org/licenses/>.
#
#
# fastq_seq_in_id: Modifies a fastq file to put the nt sequence in the ID line
#
# USAGE: ./fastq_seq_in_id <fastq_infile> > <fastq_outfile>
##


sed -e '{
N
s/\(\n\)\(.*\)/#\2\1\2/g;n;n

}' $1
