#!/bin/bash

###
# Copyright 2016 Miler T. Lee, University of Pittburgh
# This file is part of the RESA Suite
#
# RESA Suite is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# RESA Suite is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with RESA Suite.  If not, see <http://www.gnu.org/licenses/>.
#
#
# mask_genome: Creates a genome fasta that Ns out sequence outside of the input bed
# regions of interest, with a 100nt buffer
#
# Usage: ./mask_genome <utr_bed> <genome_fasta> <genome_sizes_unix_sorted> <out_fasta>
##


if [ "$1" == "-h" ]; then
    echo "Usage: mask_genome <utr_bed> <genome_fasta> <genome_sizes_unix_sorted> <out_fasta>"
    exit 1
fi


BEDTOOLS=bedtools

UTR_BED=$1
GENOME_FA=$2
CHR_SIZES=$3
OUTFASTA=$4

sort -k1,1 -k2,2n $UTR_BED | $BEDTOOLS slop -b 100 -i - -g $CHR_SIZES | $BEDTOOLS complement -i - -g $CHR_SIZES | $BEDTOOLS maskfasta -fi $GENOME_FA -bed - -fo $OUTFASTA
